name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint
      continue-on-error: true

    - name: Build project
      run: npm run build

  backend-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Check backend structure
      working-directory: ./express-backend
      run: |
        echo "Checking backend structure..."
        ls -la
        if [ -f "package.json" ]; then
          echo "✅ package.json found"
          npm install
          echo "✅ Backend dependencies installed"
        else
          echo "❌ package.json not found"
          exit 1
        fi

  quiz-backend-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Check quiz backend structure
      working-directory: ./real_time_quiz/backend
      run: |
        echo "Checking quiz backend structure..."
        ls -la
        if [ -f "package.json" ]; then
          echo "✅ package.json found"
          npm install
          echo "✅ Quiz backend dependencies installed"
        else
          echo "❌ package.json not found"
          exit 1
        fi 